### PR TITLE
Delete the beta flag in composer information

### PR DESCRIPTION
**Pull request by mojoLyon**

### CODE REVIEW

**Comment by mguillermin** [comment]
:+1:

**Comment by omansour** [comment]
:+1:

**Comment by omansour** [comment]
please release @mojoLyon :)

**Comment by mojoLyon** [comment]
it's not urgent :) 
@omansour  May be it's not necessary to make a release for these changes ?

**Comment by mikaelrandy** [comment]
:+1:

**Comment by omansour** [comment]
It's a minor release for me (like a bugfix)

**Pull request merged**
