### PR TITLE
Run tests against SF 2.3/2.7/3.0 on PHP 5.5/7.0

### PR DESCRIPTION
**Pull request by Oliboy50**
See #23 for concern about symfony versions compatibility.

### CODE REVIEW

**Comment by lolautruche** [comment]
IMHO you should at least also test with PHP 7. PHP 5.6 may also make sense...

**Comment by lolautruche** [comment]
- Symfony 2.8 and Symfony 3.1

For PHP 7 tests, maybe only test against Sf 3.x

**Comment by omansour** [comment]
"failed: object(Symfony\Component\Config\Definition\Exception\InvalidDefinitionException) is not an instance of \InvalidArgumentException"

**Comment by Oliboy50** [comment]
@omansour  I rebased and added php7 builds 👍

**Comment by omansour** [comment]
👍 any thoughts @lolautruche ?

**Comment by lolautruche** [comment]
👍 
However, I think you should also test against Symfony 3.1 as it's the current version now.

**Pull request merged**
